id: P009244
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016928
  title: གསུང་འབུམ། དགེ་འདུན་བློ་བཟང
  author: ''
  volumes:
    89309f1162c64a14a038227c809dedfe:
      image_group_id: I01JW231
      title: ''
      volume_number: 1
      total_pages: 352
      base_file: v001.txt
    bfd34316d4dd47f781bf47fb274d8ae0:
      image_group_id: I01JW232
      title: ''
      volume_number: 2
      total_pages: 348
      base_file: v002.txt
